# Generated by Django 3.2.1 on 2021-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='status',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='Aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
