# Generated by Django 3.2.1 on 2021-05-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontoturistico_atracoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name': 'Ponto turistico', 'verbose_name_plural': 'Pontos turisticos'},
        ),
        migrations.AlterModelTable(
            name='pontoturistico',
            table='ponto turistico',
        ),
    ]
