# Generated by Django 3.2.1 on 2021-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210506_1808'),
        ('core', '0005_pontoturistico_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Avaliacao'),
        ),
    ]
