# Generated by Django 3.2.1 on 2021-05-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0008_pontoturistico_endereco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
        ),
    ]
