# Generated by Django 3.2.1 on 2021-05-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pontoturistico_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='avaliacao',
        ),
    ]
