# Generated by Django 3.2.1 on 2021-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_aprovado_pontoturistico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome',
            field=models.CharField(max_length=130, verbose_name='nome'),
        ),
    ]
