# Generated by Django 3.2.1 on 2021-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_avaliacao_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='notas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
