# Generated by Django 3.2.1 on 2021-05-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pontoturistico_avaliacao'),
        ('comentarios', '0004_comentario_notas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
