# Generated by Django 3.2.1 on 2021-05-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='descrição',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='atracao',
            old_name='horario',
            new_name='Horario',
        ),
        migrations.RenameField(
            model_name='atracao',
            old_name='idade',
            new_name='Idade',
        ),
    ]
