# Generated by Django 3.2.1 on 2021-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20210505_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='Descrição',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='atracao',
            old_name='Idade',
            new_name='idade',
        ),
        migrations.RemoveField(
            model_name='atracao',
            name='Horario',
        ),
        migrations.AddField(
            model_name='atracao',
            name='horario',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
    ]
