# Generated by Django 3.2.1 on 2021-05-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20210505_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='nome',
            field=models.CharField(max_length=130, verbose_name='nome'),
        ),
    ]
