# Generated by Django 3.2.1 on 2021-05-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0004_alter_atracao_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atracao', 'verbose_name_plural': 'Atracoes'},
        ),
        migrations.AlterModelTable(
            name='atracao',
            table='atracao',
        ),
    ]
