# Generated by Django 3.2.1 on 2021-05-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0005_auto_20210505_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atraçao', 'verbose_name_plural': 'Atraçoes'},
        ),
        migrations.AlterModelTable(
            name='atracao',
            table='atraçao',
        ),
    ]
