# Generated by Django 3.2.1 on 2021-05-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0006_auto_20210505_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
