# Generated by Django 3.2.1 on 2021-05-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0007_rename_descrição_atracao_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade',
            new_name='idade_min',
        ),
    ]
