# Generated by Django 3.2.1 on 2021-05-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0009_atracao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='horario',
            field=models.CharField(max_length=130, verbose_name='horario'),
        ),
    ]
